image: node:22-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

# Define pipeline stages
stages:
  - test
  - build

# Lint job configuration: runs code quality checks using Biome
code_quality:
    image:
      name: ghcr.io/biomejs/biome:1.9.4
      entrypoint: [""]
    stage: test
    script:
        - biome ci --reporter=gitlab --colors=off ./app > gl-code-quality-report.json
    artifacts:
        when: always
        reports:
            codequality: gl-code-quality-report.json
        paths:
            - gl-code-quality-report.json    # Collect the code quality report as an artifact

unit_tests:
    stage: test
    script:
        - npm ci
        - npm run test:ci
    artifacts:
        when: always
        reports:
            junit: junit.xml
        paths:
            - coverage/
    coverage: '/All files\s+\|\s+[0-9.]+\s+\|\s+[0-9.]+\s+\|\s+[0-9.]+\s+\|\s+([0-9.]+)/'

build_web:
    stage: build
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build/client
