// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/configurations": {
    params: {};
  };
  "/configuration/:uuid": {
    params: {
      "uuid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/catalog" | "/configurations" | "/configuration/:uuid";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./layouts/auth.tsx": {
    id: "layouts/auth";
    page: "/auth";
  };
  "./routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "./layouts/main.tsx": {
    id: "layouts/main";
    page: "/catalog" | "/configurations" | "/configuration/:uuid";
  };
  "./routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/catalog";
  };
  "./routes/configurations.tsx": {
    id: "routes/configurations";
    page: "/configurations";
  };
  "./routes/configuration.tsx": {
    id: "routes/configuration";
    page: "/configuration/:uuid";
  };
};